univ = Universe.find_by_name("wheel_of_time")

#############
## Proper nouns
%w{aes_sedai agelmar aiel ajah al_ellisande aldiebamyrlin andor arafel aram tuatha'an 
  ba'alzamon baerlon bel_tine blight caemlyn cairhien carai_an_caldazar carai_an_ellisande
  darkfriend dragon dreadlord easar fade far_dareis_mai father_of_lies sightblinder
  shadowkiller forsaken gentling gleeman horn_of_valere halfman myrddraal heartfang
  heartsbane heartstone illian kandor ko'bal leafblighter lurk mahdi malkier mandarb
  manetheren maradon saldaea sightburner shayol_ghul shadowman shadar_logoth shai'tan
  shienar tar_valon tear thankan'dar tinkers trolloc whitecloaks avendesora caralain
  daes_dae'mar dai_shan corenne do_miere_a'vron draghkar forsaken gaidin goaban hardan
  hailene hardan karaethon_cycle luthair rhyagelle treekiller treesinger treesong warder
}.each{ |word| Word.add_word(:word => word, :universe_id => univ.id, :is_name => true) }

##############
## Acronyms
%w{
}.each{ |word| Word.add_word(:word => word, :universe_id => univ.id, :is_acronym => true) }

##############
## Regular Words
%w{angreal cuendillar sa'angreal saidar saidin stedding shoufa tabac ta'maral'ailen ta'veren
  a'dan alantin bittern demane marath'damane mashiara stilling sul'dam tai'shar ter'angreal
  tia_avende_alantin ti_mi_aven_moridin_isainde_vadin 
}.each{|word| Word.add_word(:word => word, :universe_id => univ.id)}


##############
## This was copied from Wikipedia's "List of characters" and cleaned up for import with search/replace

Word.add_word(:word => "Heran Adan", :definition => "Governor of Baerlon", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Logain Ablar", :definition => "Previously a False Dragon, he has become a sworn ally to Rand al'Thor and a leading Asha'man", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Jonan Adley", :definition => "Joined the Black Tower early on. Killed when Rand al'Thor lost control of Callandor in Altara", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Aginor", :definition => "One of the Forsaken", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Lelaine Akashi", :definition => "Aes Sedai sister of the Blue Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Nalesean Aldiaya", :definition => "Deceased commander of the Band of the Red Hand", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Algarin", :definition => "Tairen Lord with potential to be an Asha'man", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Alivia", :definition => "Former Seanchan damane. Most powerful female channeler alive", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Katerine Alruddin", :definition => "Black Ajah sister formerly of the Red Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Alviarin", :definition => "Black Ajah sister formerly of the White Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Amathera", :definition => "Former Panarch of Tarabon. Love interest of Juilin Sandar", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Merana Ambrey", :definition => "Aes Sedai of the Grey Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Amys", :definition => "Aiel Wise One", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Anaiya", :definition => "Aes Sedai sister of the Blue Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Setalle Anan", :definition => "Former Aes Sedai who becomes an innkeeper in Edou Bar", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Sashalle Anderly", :definition => "Aes Sedai of the Red Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Rianna Andomeran", :definition => "Black Ajah sister formerly of the White Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Anlee", :definition => "Aes Sedai sister of the Blue Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Asmodean", :definition => "One of the Forsaken", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Saerin Asnobar", :definition => "Aes Sedai sister of the Brown Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Rhadam Asunawa", :definition => "High Inquisitor, leader of the Hand of the Children of the Light", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Aviendha", :definition => "Aiel. Was a Maiden of the Spear now a, Wise One, and one of Rand al'Thor's love interests", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Perrin Aybara", :definition => "Ta'veren and a central character of the series", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Edesina Azzedin", :definition => "Aes Sedai sister of the Yellow Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Bain", :definition => "Aiel Maiden of the Spear", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Balthamel", :definition => "One of the Forsaken", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Balwer", :definition => "Secretary to Perrin Aybara", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Teslyn Baradon", :definition => "Aes Sedai of the Red Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Narenwin Barda", :definition => "Aes Sedai sister of the Yellow Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Duhara Basaheen", :definition => "Aes Sedai of the Red Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Davram Bashere", :definition => "Decorated General of Saldaea", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Faile Bashere", :definition => "Daughter of Davram Bashere. Wife of Perrin Aybara", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Adelorna Bastine", :definition => "Aes Sedai sister of the Green Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Sheriam Bayanar", :definition => "Black Ajah sister formerly of the Blue Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Be'lal", :definition => "One of the Forsaken", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Myrelle Berengari", :definition => "Aes Sedai sister of the Green Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Falion Bhoda", :definition => "Black Ajah sister formerly of the White Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Nesune Bihara", :definition => "Aes Sedai sister of the Brown Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Jesse Bilal", :definition => "Aes Sedai sister of the Brown Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Erian Boroleos", :definition => "Aes Sedai sister of the Green Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Silviana Brehon", :definition => "Aes Sedai of the Red Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Gareth Bryne", :definition => "Decorated General of Andor", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Joiya Byir", :definition => "Black Ajah sister formerly of the Grey Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Jeaine Caide", :definition => "Black Ajah sister formerly of the Green Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Gaidal Cain", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Adine Canford", :definition => "Aes Sedai sister of the Blue Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Canler", :definition => "Asha'man in the Black Tower loyal to Logain Ablar", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Carlinya", :definition => "Aes Sedai of the White Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Carlomin", :definition => "A Tairen Lord. Banner-General in the Band of the Red Hand, he leads a banner of horse in Altara", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Galina Casban", :definition => "Black Ajah sister formerly of the Red Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Romanda Cassin", :definition => "Aes Sedai sister of the Yellow Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Mat Cauthon", :definition => "POV Character. Ta'veren. Companion of Perrin Aybara and Rand al'Thor, he becomes Captain-General of the Band of the Red Hand", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Merilille Ceandevin", :definition => "Aes Sedai of the Grey Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Noal Charin", :definition => "Member of the Band of the Red Hand, met Mat after the Gholam attacked him in Ebou Dar", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Chiad", :definition => "Aiel Maiden of the Spear", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Rafela Cindal", :definition => "Aes Sedai sister of the Blue Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Couladin", :definition => "Shaido Aiel Clan chief", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Theodrin Dabei", :definition => "Aes Sedai sister of the Brown Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Zerah Dacan", :definition => "Aes Sedai of the White Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Nisao Dachen", :definition => "Aes Sedai sister of the Yellow Ajah. Her Warder is Sarin Hoigan", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Masema Dagar", :definition => "Soldier. Prophet of the Dragon", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Dagdara", :definition => "Black Ajah sister formerly of the Yellow Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Galad Damodred", :definition => "Half-brother of Elayne and Gawyn Trakand, son of Tigraine Mantear", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Moiraine Damodred", :definition => "Aes Sedai sister of the Blue Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Corlan Dashiva", :definition => "Guise of Aginor while in the Black Tower", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Cetalia Delarme", :definition => "Aes Sedai sister of the Blue Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Talmanes Delovinde", :definition => "A Lord of Cairhien. Lieutenant-General in the Band of the Red Hand, he leads the Altara contingent of three banners supplemented by a large group of crossbowmen", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Demandred", :definition => "One of the Forsaken", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Bayle Domon", :definition => "Captain of The Spray", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Norine Dovarna", :definition => "Aes Sedai of the White Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Eadyth", :definition => "Aes Sedai sister of the Blue Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Edorion", :definition => "A Tairen Lord. Banner-General in the Band of the Red Hand, he leads a banner of horse in Altara under Talmanes", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Chesmal Emry", :definition => "Black Ajah sister formerly of the Yellow Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Enkazin", :definition => "Asha'man. Friend of Saml al'Seen from the Two Rivers", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Demira Eriff", :definition => "Aes Sedai sister of the Brown Ajah. She has one Warder, Stevan", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Erith", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Estean", :definition => "Lieutenant-General in the Band of the Red Hand, he commands the cavalry of the Murandy contingent, particularly three banners of horse", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Padan Fain", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Min Farshaw", :definition => "One of Rand al'Thor's love interests", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Tarna Feir", :definition => "Aes Sedai of the Red Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Fera", :definition => "Black Ajah sister formerly of the White Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Damer Flinn", :definition => "One of the oldest Asha'man, the first to be tested for the ability by Mazrim Taim himself. Bonded as a Warder to Corele Hovian", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Andaya Forae", :definition => "Aes Sedai of the Grey Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Careane Fransi", :definition => "Black Ajah sister formerly of the Green Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Ryma Galfrey", :definition => "Aes Sedai sister of the Yellow Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Gaul", :definition => "Aiel stone dog", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Toveine Gazal", :definition => "Aes Sedai of the Red Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Charl Gedwyn", :definition => "Asha'man that was part of the plot to kill Rand al'Thor in Cairhien. Killed by Padan Fain", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Marillin Gemalphin", :definition => "Black Ajah sister formerly of the Brown Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Androl Genhald", :definition => "Asha'man in the Black Tower loyal to Logain Ablar", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Jur Grady", :definition => "One of the original Asha'man recruits. Accompanies Perrin Aybara", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Graendal", :definition => "One of the Forsaken", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Merise Haindehl", :definition => "Aes Sedai sister of the Green Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Shaidar Haran", :definition => "Named Mydrraal. A principal agent of the Dark One", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Faeldrin Harella", :definition => "Aes Sedai sister of the Green Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Bera Harkin", :definition => "Aes Sedai sister of the Green Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Harldin", :definition => "Harldin is one of the Asha'man in the Black Tower loyal to Logain Ablar", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Artur Hawkwing", :definition => "Historic general who conquered most of the Wetlands", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Seaine Herimon", :definition => "Aes Sedai of the White Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Eben Hopwil", :definition => "Asha'man bonded by Daigian Moseneillin. Killed by Aran'gar as he attempts to shield his Aes Sedai from the Forsaken's attack", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Corele Hovian", :definition => "Aes Sedai sister of the Yellow Ajah. She bonded Asha'man Damer Flinn", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Hurin", :definition => "A Sniffer", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Ishamael", :definition => "One of the Forsaken", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Rodel Ituralde", :definition => "One of the Five Great Captains. Fought the Seanchan in Tarabon, but now works for Rand al'Thor on the Saldean front", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Agelmar Jagad", :definition => "One of the Five Great Captains, leads the combined armies of the Borderlands in a search for Rand al'Thor", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Eldrith Jhondar", :definition => "Black Ajah sister formerly of the Brown Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Janduin", :definition => "Former leader of the Tardaad Aiel and biological father of Rand al'Thor. Killed by Slayer in the Blight", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Welyn Kajima", :definition => "Asha'man", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Moria Karentanis", :definition => "Aes Sedai sister of the Blue Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Temaile Kinderode", :definition => "Black Ajah sister formerly of the Gray Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Raefar Kisman", :definition => "Asha'man that was part of the plot to kill Rand al'Thor in Cairhien", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Kumira", :definition => "Aes Sedai sister of the Brown Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Mezar Kurin", :definition => "Asha'man in the Black Tower loyal to Logain Ablar", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Lanfear", :definition => "One of the Forsaken, appears as the most beautiful woman ever seen", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Annoura Larisen", :definition => "Aes Sedai of the Grey Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Atuan Larisett", :definition => "Black Ajah sister formerly of the Yellow Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Liandrin", :definition => "Black Ajah sister formerly of the Red Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Loial", :definition => "An Ogier from Stedding Shangtai, friend of Rand al'Thor", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Lyrelle", :definition => "Aes Sedai sister of the Blue Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Elyas Machera", :definition => "Wolfbrother, former Warder", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Maigan", :definition => "Aes Sedai sister of the Blue Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Arel Malevin", :definition => "Asha'man", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Mandevwin", :definition => "A Cairhienen. Banner-General in the Band of the Red Hand, he commands the crossbowmen temporarily attached to the Altaran cavalry contingent", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Lan Mandragoran", :definition => "Warder, Uncrowned-king of fallen Malkier", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Karldin Manfor", :definition => "Asha'man. Bonded as Warder by Beldeine Nyram of Green Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Tigraine Mantear", :definition => "Former queen of Andor, mother of Rand al'Thor", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Beonin Marinye", :definition => "Aes Sedai of the Grey Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Verin Mathwin", :definition => "Black Ajah sister formerly of the Brown Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Joline Maza", :definition => "Aes Sedai sister of the Green Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Nynaeve al'Meara", :definition => "POV character. Wisdom of Emond's Field and eventual Aes Sedai", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Cabriana Mecandes", :definition => "Aes Sedai sister of the Blue Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Meidani", :definition => "Aes Sedai of the Grey Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Cadsuane Melaidhrin", :definition => "Aes Sedai sister of the Green Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Thom Merrilin", :definition => "Gleeman and adventurer", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Mesaana", :definition => "One of the Forsaken", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Talene Minly", :definition => "Black Ajah sister formerly of the Green Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Atal Mishraile", :definition => "Asha'man loyal to Mazrim Taim", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Miyasi", :definition => "Black Ajah sister formerly of the White Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Ilyena Moerelle", :definition => "Wife of Lews Therin Telamon and slain by him", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Moghedien", :definition => "One of the Forsaken", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Mordeth", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Gitara Moroso", :definition => "Keeper of the Chronicles to Tamra Ospenya", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Fedwin Morr", :definition => "One of the first Asha'man. Killed by Rand al'Thor as a mercy once Morr falls victim to the taint on saidin", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Morvrin", :definition => "Aes Sedai sister of the Brown Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Delana Mosalaine", :definition => "Black Ajah sister formerly of the Grey Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Daigian Moseneillin", :definition => "Aes Sedai of the White Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Alanna Mosvani", :definition => "Aes Sedai sister of the Green Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Kiruna Nachiman", :definition => "Aes Sedai sister of the Green Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Malind Nachenin", :definition => "Aes Sedai sister of the Green Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Amico Nagoyin", :definition => "Black Ajah sister formerly of the Yellow Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Aeldra Najaf", :definition => "Aes Sedai sister of the Blue Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Arlen Nalaam", :definition => "Asha'man", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Adeleas Namelle", :definition => "Aes Sedai sister of the Brown Ajah. Twin to Vandene Namelle", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Vandene Namelle", :definition => "Aes Sedai sister of the Green Ajah. Twin to Adeleas Namelle", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Jahar Narishma", :definition => "Asha'man loyal to Rand al'Thor", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Berylla Naron", :definition => "Black Ajah sister formerly of the Blue Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Fager Neald", :definition => "Asha'man of soldier rank. Accompanies Perrin Aybara in his mission to find Masema", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Ferane Neheran", :definition => "Aes Sedai of the White Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Sarene Nemdahl", :definition => "Aes Sedai of the White Ajah. She is more than beautiful and her warder's name is Vitalien", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Varil Nensen", :definition => "Asha'man", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Pedron Niall", :definition => "Was of the Lord Captain Commander of the Children of the Light", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Norley", :definition => "Norley is one of the Asha'man in the Black Tower loyal to Logain Ablar", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Beldeine Nyram", :definition => "Aes Sedai sister of the Green Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Olver", :definition => "Orphan and companion to the Band of the Red Hand", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Daerid Ondin", :definition => "Lieutenant-General in the Band of the Red Hand, he commands five banners of foot soldiers in the Murandy group", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Faolain Orande", :definition => "Aes Sedai sister of the Blue Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Tamra Ospenya", :definition => "Historical Amyrlin Seat raised from the Blue Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Elza Penfell", :definition => "Black Ajah sister formerly of the Green Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Rahvin", :definition => "One of the Forsaken", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Tsutama Rath", :definition => "Aes Sedai of the Red Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Merean Redhill", :definition => "Black Ajah sister formerly of the Blue Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Reimon", :definition => "A Tairen Lord. Banner-General in the Band of the Red Hand, he leads a banner of horse also in Altara", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Rhuarc", :definition => "Aiel clan chief", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Manel Rochaid", :definition => "Asha'man that was part of the plot to kill Rand al'Thor in Cairhien. Killed by Rand", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Elaida a'Roihan", :definition => "Aes Sedai of the Red Ajah. Raised to Amyrlin Seat during the series, she is later replaced", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Sammael", :definition => "One of the Forsaken", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Donalo Sandomere", :definition => "Asha'man in the Black Tower loyal to Logain Ablar", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Karale Sanghir", :definition => "Black Ajah sister formerly of the Grey Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Semirhage", :definition => "One of the Forsaken", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Siuan Sanche", :definition => "Aes Sedai sister of the Blue Ajah. Former Amyrlin Seat", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Juilin Sandar", :definition => "Thief-catcher of Tear", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Saml al'Seen", :definition => "Asha'man native to Emond's Field", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Selucia Shadow & Truth speaker to Empress of Seanchan", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Leane Sharif", :definition => "Aes Sedai sister of the Green Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Ispan Shefar", :definition => "Black Ajah sister formerly of the Blue Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Birgitte Silverbow", :definition => "Hero of the Horn. Warder to Elayne Trakand", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Slayer", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Masuri Sokawa", :definition => "Aes Sedai sister of the Brown Ajah. She has one Warder, Rovair Kirklin", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Someshta", :definition => "Green Man, last of the Nym", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Sorilea", :definition => "Aiel Wise One", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Kairen Stang", :definition => "Aes Sedai sister of the Blue Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Mattin Stepaneos den Balgar", :definition => "King of Illian", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Aeldene Stonebridge", :definition => "Aes Sedai sister of the Blue Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Mazrim Taim", :definition => "Asha'man and False Dragon", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Takima", :definition => "Aes Sedai sister of the Brown Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Talmanes", :definition => "Man of the Redarms", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Samitsu Tamagowa", :definition => "Aes Sedai sister of the Yellow Ajah. Her warder is named Roshan", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Berelain sur Paendrag Tanreal", :definition => "First of Mayene", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Pevara Tazanovni", :definition => "Aes Sedai of the Red Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Lews Therin Telamon", :definition => "Dragon, Lord of Morning, Kinslayer, led the fight against the Shadow in the War of Power", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Therava Shaido", :definition => "Aiel Wise One and master of former Black Ajah Aes Sedai Galina Casban", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Rand al'Thor", :definition => "Dragon Reborn during the current War of Power", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Tam al'Thor", :definition => "Adoptive father of Rand al'Thor", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Marris Thornhill", :definition => "Black Ajah sister formerly of the Brown Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Salita Toranes", :definition => "Aes Sedai sister of the Yellow Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Peral Torval", :definition => "Asha'man that was part of the plot to kill Rand al'Thor in Cairhien. Killed by Padan Fain", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Seonid Traighan", :definition => "Aes Sedai sister of the Green Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Elayne Trakand", :definition => "Daughter-Heir to the throne of Andor, and later ascends to the throne. Aes Sedai of the Green Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Gawyn Trakand", :definition => "Brother of Elayne and son of Morgase Trakand, half-brother to Galad Damodred. Leader of the Younglings", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Morgase Trakand", :definition => "Queen of Andor. Mother of Gawyn, Elayne and Galad", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Nicola Treehill", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Tuon", :definition => "Daughter of the Nine Moons, Now Empress. Leader of the Seanchan invasion force", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Eamon Valda", :definition => "Was Lord Captain Commander of the Children of the Light", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Egwene al'Vere", :definition => "POV character from Emond's Field. Is Amyrlin Seat", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Evin Vinchova", :definition => "Asha'man in the Black Tower loyal to Logain Ablar", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Yukiri", :definition => "Aes Sedai of the Grey Ajah", :universe_id => univ.id, :is_name => true)
Word.add_word(:word => "Asne Zeramene", :definition => "Black Ajah sister formerly of the Green Ajah", :universe_id => univ.id, :is_name => true)
